### ISSUE TITLE
help wanted

### ISSUE THREAD

**Issue by DeeJaVu** [kenarkose/Chronicle#1]
Hello im creating a app where i can mark movies as favorite, watched, and seen

so i have added recordactivity to my model like this

    <?php

    namespace App;

    use Illuminate\Database\Eloquent\Model;
    use Kenarkose\Chronicle\RecordsActivity;

    class Favorite extends Model {
	    use RecordsActivity;

	    protected static $recordEvents = ['created'];

	    protected $fillable = [
		    'user_id',
		    'movie_id',
	    ];
    }

when i added a movie to my favorites table it added a new row to the activities table like this

 id | subject_id | subject_type | name | user_id | created_at 
------------ | ------------ | ------------ | ------------ | ------------ | ------------
1 | 10 | App\Favorite | created_favorite | 1 | 2015-11-19 13:23:24

and my favortie table is like this

 id | user_id | movie_id | created_at
------------ | ------------ | ------------ | ------------ 
10 | 1 | 362136 | 2015-11-19 13:23:24 

with this how can i create "user id1 has added movie362136 to the favorites list"

can this be created with Chronicle ?

**Comment by Hyleeh** [comment]
Hi!

Chronicle does not provide a built-in way to output the activity feed since that is usually app specific.

So what you can do is to retrieve records like below (depending on how you want to filter activities)...

```php
    $activity = Chronicle::getAllRecords();
    $activity = Chronicle::getRecords($limit);
    $activity = chronicle()->getUserActivity(Auth::user());
    $activity = Chronicle::getActivitiesOlderThan($carbon);
```

... and loop through them inside a view. (For demonstration purposes I'm referencing Blade)

```php
    <ul>
    @foreach($activity as $event)
        <li>{{ $event->user->username }} has added movie {{ $event->subject->movie_id }} to the favorites list.</li>
    @endforeach
    </ul>
```

You can find additional information about using Chronicle features (especially in ChronicleTest test inside tests directory and Chronicle class inside source directory)

I am planning on adding more documentation when I have more time

**Comment by DeeJaVu** [comment]
That makes sense. Thank you very much
